// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniStay.Data;

#nullable disable

namespace UniStay.Migrations
{
    [DbContext(typeof(DormitoryDbContext))]
    [Migration("20260307234230_AddRegistrationDates")]
    partial class AddRegistrationDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniStay.Models.Absence", b =>
                {
                    b.Property<int>("AbsenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AbsenceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbsenceId"));

                    b.Property<string>("AbsenceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AllocationId")
                        .HasColumnType("int")
                        .HasColumnName("AllocationID");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("DaysCount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(datediff(day,[FromDate],[ToDate])+(1))", true);

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsWeekendIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.HasKey("AbsenceId")
                        .HasName("PK__Absence__3A074E471A03DB31");

                    b.HasIndex("AllocationId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("Absence", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("DormitoryId")
                        .HasColumnType("int")
                        .HasColumnName("DormitoryID");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdminId")
                        .HasName("PK__Admin__719FE4E880AFF735");

                    b.HasIndex("DormitoryId");

                    b.HasIndex(new[] { "Username" }, "UQ__Admin__536C85E456A1733F")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Allocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AllocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AllocatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<int>("BedNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MealPlanAllocated")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<string>("Semester")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date");

                    b.HasKey("AllocationId")
                        .HasName("PK__Allocati__B3C6D6ABF8A35DA6");

                    b.HasIndex("AllocatedBy");

                    b.HasIndex("ApplicationId");

                    b.HasIndex(new[] { "RoomId" }, "IDX_Allocation_RoomID");

                    b.HasIndex(new[] { "StudentId" }, "UQ_ActiveAllocation")
                        .IsUnique()
                        .HasFilter("([IsActive]=(1) AND [IsDeleted]=(0))");

                    b.HasIndex(new[] { "RoomId", "BedNumber" }, "UQ_BedAllocation")
                        .IsUnique()
                        .HasFilter("([IsActive]=(1) AND [IsDeleted]=(0))");

                    b.ToTable("Allocation", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AnnouncementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DormitoryId")
                        .HasColumnType("int")
                        .HasColumnName("DormitoryID");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("int")
                        .HasColumnName("UniversityID");

                    b.HasKey("AnnouncementId")
                        .HasName("PK__Announce__9DE44554A69D832F");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DormitoryId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Announcement", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.AnnouncementAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttachmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int")
                        .HasColumnName("AnnouncementID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("AttachmentId")
                        .HasName("PK__Announce__442C64DE72D109DF");

                    b.HasIndex("AnnouncementId");

                    b.ToTable("AnnouncementAttachment", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool?>("FamilyAbroad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("HousingPreference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MealPlanType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PreferredBedNumber")
                        .HasColumnType("int");

                    b.Property<int?>("PreferredBuildingId")
                        .HasColumnType("int")
                        .HasColumnName("PreferredBuildingID");

                    b.Property<int?>("PreferredRoomId")
                        .HasColumnType("int")
                        .HasColumnName("PreferredRoomID");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredDocuments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("SpecialNeeds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("WithoutNutrition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ApplicationId")
                        .HasName("PK__Applicat__C93A4F79D368EB6C");

                    b.HasIndex("PreferredBuildingId");

                    b.HasIndex("PreferredRoomId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex(new[] { "HousingPreference" }, "IDX_Application_Preference");

                    b.HasIndex(new[] { "Status" }, "IDX_Application_Status");

                    b.HasIndex(new[] { "StudentId", "AcademicYear", "Semester" }, "UQ_App_Student_Year")
                        .IsUnique()
                        .HasFilter("([IsDeleted]=(0))");

                    b.ToTable("Application", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.ApplicationSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("DormitoryId")
                        .HasColumnType("int")
                        .HasColumnName("DormitoryID");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("StudentCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Applicat__9C8A5B69868F8CF2");

                    b.HasIndex("DormitoryId");

                    b.ToTable("ApplicationSchedule", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BuildingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("DormitoryId")
                        .HasColumnType("int")
                        .HasColumnName("DormitoryID");

                    b.Property<int?>("FloorsCount")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("TotalRooms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(150);

                    b.HasKey("BuildingId")
                        .HasName("PK__Building__5463CDE4A6F80590");

                    b.HasIndex("DormitoryId");

                    b.HasIndex(new[] { "BuildingType" }, "IDX_Building_Type");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DocumentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.HasKey("DocumentId")
                        .HasName("PK__Document__1ABEEF6F35C9E87F");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("StudentId");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("Document", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Dormitory", b =>
                {
                    b.Property<int>("DormitoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DormitoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DormitoryId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("DormitoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int")
                        .HasColumnName("UniversityID");

                    b.HasKey("DormitoryId")
                        .HasName("PK__Dormitor__14188ACE157AEAF1");

                    b.HasIndex("UniversityId");

                    b.ToTable("Dormitory", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.EvictionNotice", b =>
                {
                    b.Property<int>("EvictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EvictionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvictionId"));

                    b.Property<int?>("AllocationId")
                        .HasColumnType("int")
                        .HasColumnName("AllocationID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("NoticeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("EvictionId")
                        .HasName("PK__Eviction__A889DE2E7895F278");

                    b.HasIndex("AllocationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StudentId");

                    b.ToTable("EvictionNotice", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Guardian", b =>
                {
                    b.Property<int>("GuardianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GuardianID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuardianId"));

                    b.Property<string>("AlternatePhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("GuardianRole")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Job")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NationalID");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Relation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResidenceAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("GuardianId")
                        .HasName("PK__Guardian__0A5E1B7BA9195463");

                    b.HasIndex("StudentId");

                    b.ToTable("Guardian", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("IssueType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId")
                        .HasName("PK__Maintena__33A8519A754946C8");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("RoomId");

                    b.HasIndex("StudentId");

                    b.ToTable("MaintenanceRequest", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MealID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealId"));

                    b.Property<int?>("AllocationId")
                        .HasColumnType("int")
                        .HasColumnName("AllocationID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool?>("IsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("MealDate")
                        .HasColumnType("date");

                    b.Property<string>("MealType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("MissedPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<DateTime?>("TakenAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MealId")
                        .HasName("PK__Meal__ACF6A65D83EC72C7");

                    b.HasIndex("AllocationId");

                    b.HasIndex(new[] { "MealDate" }, "IDX_Meal_Date");

                    b.HasIndex(new[] { "StudentId" }, "IDX_Meal_StudentID");

                    b.HasIndex(new[] { "StudentId", "MealDate", "MealType" }, "UQ__Meal__3449321F74EFBA23")
                        .IsUnique()
                        .HasFilter("[StudentID] IS NOT NULL AND [MealDate] IS NOT NULL AND [MealType] IS NOT NULL");

                    b.ToTable("Meal", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("AllocationId")
                        .HasColumnType("int")
                        .HasColumnName("AllocationID");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EvictionNoticeIssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstWarningSentAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsOverdue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PaymentCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ReceivedBy")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__9B556A58940BC47E");

                    b.HasIndex("AllocationId");

                    b.HasIndex("ReceivedBy");

                    b.HasIndex(new[] { "PaymentCategory" }, "IDX_Payment_Category");

                    b.HasIndex(new[] { "StudentId" }, "IDX_Payment_StudentID");

                    b.HasIndex(new[] { "ReceiptNumber" }, "UQ__Payment__C08AFDAB02FB820D")
                        .IsUnique()
                        .HasFilter("[ReceiptNumber] IS NOT NULL");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.RegistrationDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RegistrationDates");
                });

            modelBuilder.Entity("UniStay.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int?>("BedsCount")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int")
                        .HasColumnName("BuildingID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("CurrentOccupancy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("FloorMaterial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("HasAc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("HasAC");

                    b.Property<bool?>("HasBalcony")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("HasFridge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("HasPrivateBathroom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoomId")
                        .HasName("PK__Room__328639197573C58E");

                    b.HasIndex("BuildingId");

                    b.HasIndex(new[] { "CurrentOccupancy" }, "IDX_Room_Occupancy");

                    b.HasIndex(new[] { "RoomType" }, "IDX_Room_Type");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AdminRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<double?>("DistanceFromHome")
                        .HasColumnType("float");

                    b.Property<bool?>("DrugTestPassed")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("FamilyAbroad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("FatherJob")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FatherName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FatherNationalId")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("FatherNationalID");

                    b.Property<string>("FatherPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullNameArabic")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Grade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("GradePercentage")
                        .HasColumnType("float");

                    b.Property<bool?>("HasMedicalCondition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("HighSchoolDivision")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("HighSchoolFromAbroad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double?>("HighSchoolPercentage")
                        .HasColumnType("float");

                    b.Property<double?>("HighSchoolTotal")
                        .HasColumnType("float");

                    b.Property<string>("HousingType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastYearGrade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("LastYearPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NationalID");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Egyptian");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassportIssuePlace")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreviousHousingYears")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Religion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Residence")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.Property<int?>("ResidenceCity")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("ResidenceCountry")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("مصر");

                    b.Property<int?>("ResidenceGovernorate")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("SpecialNeeds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("New");

                    b.Property<string>("StudyType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__32C52A79F8FED0B2");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "IDX_Student_Email");

                    b.HasIndex(new[] { "NationalId" }, "IDX_Student_NationalID");

                    b.HasIndex(new[] { "Nationality" }, "IDX_Student_Nationality");

                    b.HasIndex(new[] { "StudentStatus" }, "IDX_Student_Status");

                    b.HasIndex(new[] { "NationalId" }, "UQ__Student__E9AA321A798CF797")
                        .IsUnique()
                        .HasFilter("[NationalID] IS NOT NULL");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.StudentDownloadLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime?>("DownloadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("LogId")
                        .HasName("PK__StudentD__5E5499A837B7D305");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentDownloadLog", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.StudentLogin", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LoginID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NationalID");

                    b.Property<byte[]>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("LoginId")
                        .HasName("PK__StudentL__4DDA28384EF1ECE5");

                    b.HasIndex(new[] { "StudentId" }, "UQ__StudentL__32C52A78F048A48E")
                        .IsUnique();

                    b.HasIndex(new[] { "NationalId" }, "UQ__StudentL__E9AA321A22477898")
                        .IsUnique();

                    b.ToTable("StudentLogin", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.University", b =>
                {
                    b.Property<int>("UniversityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UniversityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UniversityId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Governorate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UniversityId")
                        .HasName("PK__Universi__9F19E19C102D5BC8");

                    b.ToTable("University", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Violation", b =>
                {
                    b.Property<int>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ViolationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViolationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Penalty")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PenaltyAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("RecordedBy")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<DateOnly?>("ViolationDate")
                        .HasColumnType("date");

                    b.Property<string>("ViolationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ViolationId")
                        .HasName("PK__Violatio__18B6DC2893B67D33");

                    b.HasIndex("RecordedBy");

                    b.HasIndex(new[] { "StudentId" }, "IDX_Violation_StudentID");

                    b.ToTable("Violation", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.VwRoomOccupancy", b =>
                {
                    b.Property<int?>("AvailableBeds")
                        .HasColumnType("int");

                    b.Property<int?>("BedsCount")
                        .HasColumnType("int");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CurrentOccupancy")
                        .HasColumnType("int");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("OccupancyStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable((string)null);

                    b.ToView("VW_RoomOccupancy", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.VwStudentStatus", b =>
                {
                    b.Property<string>("AcademicYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("BedNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BuildingType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("DistanceFromHome")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("FamilyAbroad")
                        .HasColumnType("bit");

                    b.Property<string>("FatherName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FatherPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullNameArabic")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Grade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("GradePercentage")
                        .HasColumnType("float");

                    b.Property<string>("HighSchoolDivision")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("HighSchoolPercentage")
                        .HasColumnType("float");

                    b.Property<string>("HousingType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsCurrentlyResident")
                        .HasColumnType("bit");

                    b.Property<string>("LastYearGrade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("LastYearPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NationalID");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ParentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Religion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Residence")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("SpecialNeeds")
                        .HasColumnType("bit");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<string>("StudentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable((string)null);

                    b.ToView("VW_StudentStatus", (string)null);
                });

            modelBuilder.Entity("UniStay.Models.Absence", b =>
                {
                    b.HasOne("UniStay.Models.Allocation", "Allocation")
                        .WithMany("Absences")
                        .HasForeignKey("AllocationId")
                        .HasConstraintName("FK__Absence__Allocat__498EEC8D");

                    b.HasOne("UniStay.Models.Admin", "ApprovedByNavigation")
                        .WithMany("Absences")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__Absence__Approve__4A8310C6");

                    b.HasOne("UniStay.Models.Student", "Student")
                        .WithMany("Absences")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Absence__Student__489AC854");

                    b.Navigation("Allocation");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniStay.Models.Admin", b =>
                {
                    b.HasOne("UniStay.Models.Dormitory", "Dormitory")
                        .WithMany("Admins")
                        .HasForeignKey("DormitoryId")
                        .HasConstraintName("FK__Admin__Dormitory__06CD04F7");

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("UniStay.Models.Allocation", b =>
                {
                    b.HasOne("UniStay.Models.Admin", "AllocatedByNavigation")
                        .WithMany("Allocations")
                        .HasForeignKey("AllocatedBy")
                        .HasConstraintName("FK__Allocatio__Alloc__25518C17");

                    b.HasOne("UniStay.Models.Application", "Application")
                        .WithMany("Allocations")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK__Allocatio__Appli__22751F6C");

                    b.HasOne("UniStay.Models.Room", "Room")
                        .WithMany("Allocations")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK__Allocatio__RoomI__245D67DE");

                    b.HasOne("UniStay.Models.Student", "Student")
                        .WithOne("Allocation")
                        .HasForeignKey("UniStay.Models.Allocation", "StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Allocatio__Stude__236943A5");

                    b.Navigation("AllocatedByNavigation");

                    b.Navigation("Application");

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniStay.Models.Announcement", b =>
                {
                    b.HasOne("UniStay.Models.Admin", "CreatedByNavigation")
                        .WithMany("Announcements")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Announcem__Creat__6AEFE058");

                    b.HasOne("UniStay.Models.Dormitory", "Dormitory")
                        .WithMany("Announcements")
                        .HasForeignKey("DormitoryId")
                        .HasConstraintName("FK__Announcem__Dormi__69FBBC1F");

                    b.HasOne("UniStay.Models.University", "University")
                        .WithMany("Announcements")
                        .HasForeignKey("UniversityId")
                        .HasConstraintName("FK__Announcem__Unive__690797E6");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Dormitory");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniStay.Models.AnnouncementAttachment", b =>
                {
                    b.HasOne("UniStay.Models.Announcement", "Announcement")
                        .WithMany("AnnouncementAttachments")
                        .HasForeignKey("AnnouncementId")
                        .IsRequired()
                        .HasConstraintName("FK__Announcem__Annou__6FB49575");

                    b.Navigation("Announcement");
                });

            modelBuilder.Entity("UniStay.Models.Application", b =>
                {
                    b.HasOne("UniStay.Models.Building", "PreferredBuilding")
                        .WithMany("Applications")
                        .HasForeignKey("PreferredBuildingId")
                        .HasConstraintName("FK__Applicati__Prefe__1BC821DD");

                    b.HasOne("UniStay.Models.Room", "PreferredRoom")
                        .WithMany("Applications")
                        .HasForeignKey("PreferredRoomId")
                        .HasConstraintName("FK__Applicati__Prefe__1CBC4616");

                    b.HasOne("UniStay.Models.Admin", "ReviewedByNavigation")
                        .WithMany("Applications")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("FK__Applicati__Revie__1AD3FDA4");

                    b.HasOne("UniStay.Models.Student", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__Stude__19DFD96B");

                    b.Navigation("PreferredBuilding");

                    b.Navigation("PreferredRoom");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniStay.Models.ApplicationSchedule", b =>
                {
                    b.HasOne("UniStay.Models.Dormitory", "Dormitory")
                        .WithMany("ApplicationSchedules")
                        .HasForeignKey("DormitoryId")
                        .HasConstraintName("FK__Applicati__Dormi__0D7A0286");

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("UniStay.Models.Building", b =>
                {
                    b.HasOne("UniStay.Models.Dormitory", "Dormitory")
                        .WithMany("Buildings")
                        .HasForeignKey("DormitoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Building__Dormit__59063A47");

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("UniStay.Models.Document", b =>
                {
                    b.HasOne("UniStay.Models.Application", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("FK__Document__Applic__607251E5");

                    b.HasOne("UniStay.Models.Student", "Student")
                        .WithMany("Documents")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Document__Studen__6166761E");

                    b.HasOne("UniStay.Models.Admin", "VerifiedByNavigation")
                        .WithMany("Documents")
                        .HasForeignKey("VerifiedBy")
                        .HasConstraintName("FK__Document__Verifi__625A9A57");

                    b.Navigation("Application");

                    b.Navigation("Student");

                    b.Navigation("VerifiedByNavigation");
                });

            modelBuilder.Entity("UniStay.Models.Dormitory", b =>
                {
                    b.HasOne("UniStay.Models.University", "University")
                        .WithMany("Dormitories")
                        .HasForeignKey("UniversityId")
                        .IsRequired()
                        .HasConstraintName("FK__Dormitory__Unive__5165187F");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniStay.Models.EvictionNotice", b =>
                {
                    b.HasOne("UniStay.Models.Allocation", "Allocation")
                        .WithMany("EvictionNotices")
                        .HasForeignKey("AllocationId")
                        .HasConstraintName("FK__EvictionN__Alloc__367C1819");

                    b.HasOne("UniStay.Models.Admin", "CreatedByNavigation")
                        .WithMany("EvictionNotices")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__EvictionN__Creat__37703C52");

                    b.HasOne("UniStay.Models.Student", "Student")
                        .WithMany("EvictionNotices")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__EvictionN__Stude__3587F3E0");

                    b.Navigation("Allocation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniStay.Models.Guardian", b =>
                {
                    b.HasOne("UniStay.Models.Student", "Student")
                        .WithMany("Guardians")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Guardian__Studen__7F2BE32F");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniStay.Models.MaintenanceRequest", b =>
                {
                    b.HasOne("UniStay.Models.Admin", "AssignedToNavigation")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK__Maintenan__Assig__5AB9788F");

                    b.HasOne("UniStay.Models.Room", "Room")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK__Maintenan__RoomI__58D1301D");

                    b.HasOne("UniStay.Models.Student", "Student")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Maintenan__Stude__59C55456");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniStay.Models.Meal", b =>
                {
                    b.HasOne("UniStay.Models.Allocation", "Allocation")
                        .WithMany("Meals")
                        .HasForeignKey("AllocationId")
                        .HasConstraintName("FK__Meal__Allocation__41EDCAC5");

                    b.HasOne("UniStay.Models.Student", "Student")
                        .WithMany("Meals")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Meal__StudentID__40F9A68C");

                    b.Navigation("Allocation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniStay.Models.Payment", b =>
                {
                    b.HasOne("UniStay.Models.Allocation", "Allocation")
                        .WithMany("Payments")
                        .HasForeignKey("AllocationId")
                        .HasConstraintName("FK__Payment__Allocat__2EDAF651");

                    b.HasOne("UniStay.Models.Admin", "ReceivedByNavigation")
                        .WithMany("Payments")
                        .HasForeignKey("ReceivedBy")
                        .HasConstraintName("FK__Payment__Receive__2FCF1A8A");

                    b.HasOne("UniStay.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Payment__Student__2DE6D218");

                    b.Navigation("Allocation");

                    b.Navigation("ReceivedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniStay.Models.Room", b =>
                {
                    b.HasOne("UniStay.Models.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .IsRequired()
                        .HasConstraintName("FK__Room__BuildingID__66603565");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("UniStay.Models.StudentDownloadLog", b =>
                {
                    b.HasOne("UniStay.Models.Student", "Student")
                        .WithMany("StudentDownloadLogs")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentDo__Stude__7B264821");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniStay.Models.StudentLogin", b =>
                {
                    b.HasOne("UniStay.Models.Student", "Student")
                        .WithOne("StudentLogin")
                        .HasForeignKey("UniStay.Models.StudentLogin", "StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentLo__Stude__7755B73D");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniStay.Models.Violation", b =>
                {
                    b.HasOne("UniStay.Models.Admin", "RecordedByNavigation")
                        .WithMany("Violations")
                        .HasForeignKey("RecordedBy")
                        .HasConstraintName("FK__Violation__Recor__5224328E");

                    b.HasOne("UniStay.Models.Student", "Student")
                        .WithMany("Violations")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Violation__Stude__51300E55");

                    b.Navigation("RecordedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniStay.Models.Admin", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Allocations");

                    b.Navigation("Announcements");

                    b.Navigation("Applications");

                    b.Navigation("Documents");

                    b.Navigation("EvictionNotices");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("Payments");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("UniStay.Models.Allocation", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("EvictionNotices");

                    b.Navigation("Meals");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("UniStay.Models.Announcement", b =>
                {
                    b.Navigation("AnnouncementAttachments");
                });

            modelBuilder.Entity("UniStay.Models.Application", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("UniStay.Models.Building", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("UniStay.Models.Dormitory", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Announcements");

                    b.Navigation("ApplicationSchedules");

                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("UniStay.Models.Room", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Applications");

                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("UniStay.Models.Student", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Allocation");

                    b.Navigation("Applications");

                    b.Navigation("Documents");

                    b.Navigation("EvictionNotices");

                    b.Navigation("Guardians");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("Meals");

                    b.Navigation("Payments");

                    b.Navigation("StudentDownloadLogs");

                    b.Navigation("StudentLogin");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("UniStay.Models.University", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Dormitories");
                });
#pragma warning restore 612, 618
        }
    }
}
